###############################################################################
### Seeded default-path compatibility: 27-Aug baseline versus PoA patch
### New InfoTriggered arguments are NOT supplied. The test compares existing
### biological/legacy output fields only.
###############################################################################
args<-commandArgs(trailingOnly=TRUE);root<-if(length(args))normalizePath(args[1],mustWork=TRUE)else normalizePath(getwd(),mustWork=TRUE)
base_dir<-file.path(root,"validation","baseline_2026-08-27");patch_dir<-file.path(root,"source");if(!dir.exists(patch_dir))patch_dir<-file.path(root,"..","..","definitive_source");out_dir<-file.path(root,"validation_output","default_backward_compatibility");dir.create(out_dir,recursive=TRUE,showWarnings=FALSE)
res<-list();k<-0L
run<-function(id,arch,fun){k<<-k+1L;status<-"PASS";detail<-"";t0<-proc.time()[3];tryCatch({detail<-fun()},error=function(e){status<<-"FAIL";detail<<-conditionMessage(e)});res[[k]]<<-data.frame(test_id=id,architecture=arch,status=status,detail=as.character(detail),elapsed_seconds=proc.time()[3]-t0,stringsAsFactors=FALSE);cat(id,status,arch,"\n")}
assert_equal<-function(a,b,msg){z<-all.equal(a,b,check.attributes=TRUE);if(!isTRUE(z))stop(msg,": ",paste(z,collapse=" | "),call.=FALSE)}
env_pair<-function(file){b<-new.env(parent=.GlobalEnv);p<-new.env(parent=.GlobalEnv);sys.source(file.path(base_dir,file),b);sys.source(file.path(patch_dir,file),p);list(b=b,p=p)}

run("BC01","INApest",function(){e<-env_pair("INApest.R");a<-list(ModelName="b",Nperm=4,Ntimesteps=2,DetectionProb=.25,DetectionSD=.02,ManageProb=.3,ManageSD=.02,EradicationProb=.2,EradicationSD=.02,SpreadReduction=.1,SpreadReductionSD=.01,InitialInvasion=c(1,0),InitialInfo=c(0,0),InfoRetentionProb=1,EnvEstabProb=1,Survival=.95,SDDprob=diag(2),LDDprob=0,SEAM=0,SaveResults=FALSE,DoPlots=FALSE,Seed=313);zb<-do.call(e$b$INApest,a);zp<-do.call(e$p$INApest,a);for(n in c("InvasionResults","ManagingResults","DetectedResults","PathogenPresentResults"))assert_equal(zb[[n]],zp[[n]],n);"seeded legacy fields identical"})

meta_fixture<-function(out){list(ModelName="m_",Nperm=3,Ntimesteps=2,DetectionProb=.2,DetectionSD=.01,ManageProb=.2,ManageSD=.01,MortalityProb=.1,MortalitySD=.01,FecundityReduction=0,SpreadReduction=.1,SpreadReductionSD=.01,InitialPopulation=c(3,0),InitBioP=NA,InvasionRisk=c(0,0),InitialInfo=c(0,0),InitInfoP=NA,ExternalInfoProb=c(0,0),InfoRetentionProb=1,InfoPersistenceSteps=NA,EnvEstabProb=1,Survival=.95,K=c(20,20),PropaguleProduction=0,PropaguleEstablishment=0,IncursionStartPop=1,SDDprob=diag(2),SEAM=0,LDDprob=NA,LDDrate=0,OngoingExternalInvasion=FALSE,OngoingExternalInfo=FALSE,OutputDir=paste0(out,"/"),DoPlots=FALSE)}
run("BC02","INApestMeta",function(){e<-env_pair("INApestMeta.r");d1<-tempfile("base_meta_");d2<-tempfile("patch_meta_");dir.create(d1);dir.create(d2);set.seed(313);do.call(e$b$INApestMeta,meta_fixture(d1));set.seed(313);do.call(e$p$INApestMeta,meta_fixture(d2));for(suf in c("InvasionLargeOut.rds","PopulationLargeOut.rds","InfoLargeOut.rds","DetectedLargeOut.rds"))assert_equal(readRDS(file.path(d1,paste0("m_",suf))),readRDS(file.path(d2,paste0("m_",suf))),suf);"seeded legacy files identical"})

mlu_fixture<-function(out){list(ModelName="u_",Nperm=2,Ntimesteps=2,Nlanduses=2,DetectionProb=c(.2,.3),DetectionSD=c(.01,.01),ManageProb=c(.2,.2),ManageSD=c(.01,.01),MortalityProb=c(.1,.1),MortalitySD=c(.01,.01),FecundityReduction=c(0,0),SpreadReduction=c(.1,.1),SpreadReductionSD=c(.01,.01),InitialPopulation=matrix(c(3,0,0,0),2,2),InitBioP=NA,InvasionRisk=c(0,0),InitialInfo=c(0,0),InitInfoP=NA,ExternalInfoProb=c(0,0),InfoRetentionProb=1,InfoPersistenceSteps=NA,EnvEstabProb=1,Survival=.95,K=matrix(20,2,2),PropaguleProduction=0,PropaguleEstablishment=0,IncursionStartPop=1,SDDprob=diag(2),SEAM=0,LDDprob=NA,LDDrate=0,OngoingExternalInvasion=FALSE,OngoingExternalInfo=FALSE,OutputDir=paste0(out,"/"),DoPlots=FALSE)}
run("BC03","INApestMetaMultipleLandUse",function(){e<-env_pair("INApestMetaMultipleLandUse.r");d1<-tempfile("base_mlu_");d2<-tempfile("patch_mlu_");dir.create(d1);dir.create(d2);set.seed(313);do.call(e$b$INApestMetaMultipleLandUse,mlu_fixture(d1));set.seed(313);do.call(e$p$INApestMetaMultipleLandUse,mlu_fixture(d2));for(suf in c("InvasionLargeOut.rds","PopulationLargeOut.rds","InfoLargeOut.rds","DetectedLargeOut.rds"))assert_equal(readRDS(file.path(d1,paste0("u_",suf))),readRDS(file.path(d2,paste0("u_",suf))),suf);"seeded legacy files identical"})

tm_fixture<-function(out){list(ModelName="t_",Nperm=2,Ntimesteps=2,Nstages=2,Weights=c(1,1),Transition=diag(2),DetectionProb=c(.2,.3),DetectionSD=matrix(.01,2,2),ManageProb=.2,ManageSD=.01,MortalityProb=c(.1,.1),MortalitySD=matrix(.01,2,2),FecundityReduction=0,SpreadReduction=.1,SpreadReductionSD=.01,InitialPopulation=matrix(c(0,3,0,0),2,2),InitBioP=NA,InvasionRisk=c(0,0),InitialInfo=c(0,0),InitInfoP=NA,ExternalInfoProb=0,InfoRetentionProb=1,InfoPersistenceSteps=NA,EnvEstabProb=1,K=c(20,20),SeedbankK=c(20,20),PropaguleEstablishment=0,IncursionStartPop=1,SDDprob=diag(2),SEAM=0,LDDprob=NA,LDDrate=0,OngoingExternalInvasion=FALSE,OngoingExternalInfo=FALSE,OutputDir=paste0(out,"/"),DoPlots=FALSE)}
run("BC04","INApestMetaTransitionMatrix",function(){e<-env_pair("INApestMetaTransitionMatrix.r");d1<-tempfile("base_tm_");d2<-tempfile("patch_tm_");dir.create(d1);dir.create(d2);set.seed(313);do.call(e$b$INApestMetaTransitionMatrix,tm_fixture(d1));set.seed(313);do.call(e$p$INApestMetaTransitionMatrix,tm_fixture(d2));for(suf in c("InvasionLargeOut.rds","PopulationLargeOut.rds","InfoLargeOut.rds","DetectedLargeOut.rds"))assert_equal(readRDS(file.path(d1,paste0("t_",suf))),readRDS(file.path(d2,paste0("t_",suf))),suf);"seeded legacy files identical"})

common_df_equal<-function(a,b,exclude=character()){nm<-setdiff(intersect(names(a),names(b)),exclude);assert_equal(a[,nm,drop=FALSE],b[,nm,drop=FALSE],paste("common columns",paste(nm,collapse=",")))}
run("BC05","INApestMetaPoint",function(){e<-env_pair("INApestMetaPoint.R");kb<-e$b$INApestPointKernelFixed(0);kp<-e$p$INApestPointKernelFixed(0);a<-list(ModelName="p",Nperm=3,Ntimesteps=2,InitialPoints=data.frame(x=0,y=0),Survival=.9,PropaguleProduction=0,PropaguleEstablishment=0,DetectionProb=.2,DetectionSD=.01,ManageProb=.1,ManageSD=.01,MortalityProb=.1,MortalitySD=.01,InitialInfo=FALSE,InfoRetentionProb=1,SaveResults=FALSE,DoProgress=FALSE,Seed=313);ab<-a;ap<-a;ab$SDDkernel<-kb;ap$SDDkernel<-kp;zb<-do.call(e$b$INApestMetaPoint,ab);zp<-do.call(e$p$INApestMetaPoint,ap);common_df_equal(zb$Summary,zp$Summary);common_df_equal(zb$FinalPoints,zp$FinalPoints);common_df_equal(zb$PointHistory,zp$PointHistory,c("have_info_before_surveillance","background_detection_prob","info_triggered_detection_prob"));"seeded biological point outputs identical"})

run("BC06","INApestPointTransitionMatrix",function(){e<-env_pair("INApestPointTransitionMatrix.R");kb<-e$b$INApestPointKernelFixed(0);kp<-e$p$INApestPointKernelFixed(0);a<-list(ModelName="q",Nperm=2,Ntimesteps=2,Nstages=2,Weights=c(1,1),Transition=diag(2),InitialPoints=data.frame(x=0,y=0,stage=2L),PropaguleEstablishment=0,DetectionProb=.2,DetectionSD=.01,ManageProb=.1,ManageSD=.01,MortalityProb=.1,MortalitySD=.01,InitialInfo=FALSE,InfoRetentionProb=1,SaveResults=FALSE,DoProgress=FALSE,Seed=313);ab<-a;ap<-a;ab$SDDkernel<-kb;ap$SDDkernel<-kp;zb<-do.call(e$b$INApestPointTransitionMatrix,ab);zp<-do.call(e$p$INApestPointTransitionMatrix,ap);common_df_equal(zb$Summary,zp$Summary);common_df_equal(zb$FinalPoints,zp$FinalPoints);common_df_equal(zb$PointHistory,zp$PointHistory,c("have_info_before_surveillance","background_detection_prob","info_triggered_detection_prob"));"seeded biological point-TM outputs identical"})

x<-do.call(rbind,res);utils::write.csv(x,file.path(out_dir,"default_backward_compatibility_results.csv"),row.names=FALSE);summary<-c("Default-path seeded backward compatibility",paste0("R: ",R.version.string),paste0("PASS: ",sum(x$status=="PASS")," / ",nrow(x)),paste0("FAIL: ",sum(x$status=="FAIL")),"",paste(x$test_id,x$status,x$architecture,sep=" | "));writeLines(summary,file.path(out_dir,"default_backward_compatibility_summary.txt"));capture.output(sessionInfo(),file=file.path(out_dir,"sessionInfo.txt"));cat(paste(summary,collapse="\n"),"\n");if(any(x$status=="FAIL"))quit(status=1L)
