###############################################################################
# INApestVNRK4CoupledBiologyLocalDynamics.R -- H+B / H+P+B for Vertebrate Node
# v0.8 -- 1 October 2026
###############################################################################
INApestVNRK4CoupledBiologyLocalDynamics <- function(HostFluxFunction,BiocontrolRates,PathogenRates=NULL,StageMixing=NULL,TimestepLength=1,RKMaxStep=0.025,HostParameters=NULL,StartTime=0,TransitionDynamics=NULL,PathogenTransitionDynamics=NULL,CapacityTolerance=1e-9){
  if(!is.function(HostFluxFunction)||!inherits(BiocontrolRates,"INApestContinuousBiocontrolRates"))stop("Invalid Vertebrate coupled-biology specification")
  if(!is.null(PathogenRates)&&!inherits(PathogenRates,"INApestContinuousPathogenRates"))stop("PathogenRates must be NULL or INApestContinuousPathogenRates")
  if(is.null(TransitionDynamics))TransitionDynamics<-get(".iv_local_dynamics_transition_matrix",mode="function")
  if(is.null(PathogenTransitionDynamics))PathogenTransitionDynamics<-get(".iv_node_pathogen_transport",mode="function")
  hf<-HostFluxFunction;br<-BiocontrolRates;pr<-PathogenRates;pars<-HostParameters;sm<-StageMixing;dt<-as.numeric(TimestepLength)[1L];hmax<-as.numeric(RKMaxStep)[1L];t0<-as.numeric(StartTime)[1L];disc<-TransitionDynamics;pdisc<-PathogenTransitionDynamics;tol<-as.numeric(CapacityTolerance)[1L];cp<-!is.null(pr)
  f<-function(nodetransition,weights,sddprob,nodeenvestabprob,n0,lddprob=NA,lddrate=0,nodeK,node.seedbankK,nodepropaguleestablishment,nodespreadreduction,managing,MaxInteger=.Machine$integer.max,nodefecundityreduction=0,nodecontrolfecundityreduction=0,nodebirthmean=NULL,nodebirthmothers=NULL,transition_sddprob=NULL,transition_lddprob=NULL,transition_lddrate=0,BlockedTransitionMortality=0,DispersalDensityFactor=0,biocontrol_state,biocontrol,biocontrol_engine,biocontrol_context,pathogen_state=NULL,Pathogen=NULL,timestep=NULL,Ntimesteps=NULL,StageMixing=NULL){
    N0<-as.matrix(n0);nn<-nrow(N0);D<-ncol(N0);nu<-nn*D;si<-if(is.null(timestep))1L else as.integer(timestep)[1L];nts<-if(is.null(Ntimesteps))1L else as.integer(Ntimesteps)[1L]
    if(is.null(biocontrol)||!inherits(biocontrol,"INApestBiocontrol"))stop("Coupled Vertebrate biology requires Biocontrol")
    agents<-biocontrol$Agents;if(!identical(names(br),names(agents)))stop("BiocontrolRates names must match agent names");if(!is.list(biocontrol_state)||!identical(names(biocontrol_state),names(agents)))stop("biocontrol_state mismatch")
    if(cp){if(is.null(Pathogen)||!inherits(Pathogen,"INApestPathogen")||Pathogen$Model=="Binary")stop("H+P+B requires non-binary Pathogen");if(any(.iptm_resolve(Pathogen$IntroductionProb,si,nn,D,nts,"IntroductionProb",TRUE)!=0))stop("Continuous Vertebrate H+P+B v0.8 requires Pathogen$IntroductionProb = 0");Hstate<-.inapest_tm_pathogen_flat(.iptm_reconcile(pathogen_state,N0));if(any(rowSums(Hstate)!=.inapest_tm_flat(N0)))stop("pathogen_state must sum stage-wise to N")}else Hstate<-matrix(as.integer(.inapest_tm_flat(N0)),ncol=1L,dimnames=list(NULL,"H"))
    Astate<-biocontrol_state
    for(nm in names(agents)){a<-agents[[nm]];rel<-.inabc_resolve_state_matrix(a$Release,si,biocontrol_context,a,"Release");z<-as.matrix(Astate[[nm]])+matrix(as.integer(round(rel)),nrow(Astate[[nm]]),ncol(Astate[[nm]]),dimnames=dimnames(Astate[[nm]]));storage.mode(z)<-"integer";Astate[[nm]]<-z}
    attacks<-lapply(agents,function(a)matrix(0L,nn,D));names(attacks)<-names(agents);deaths<-matrix(0L,nn,D)
    nsub<-max(1L,as.integer(ceiling(dt/hmax-1e-14)));h<-dt/nsub;tt<-t0+(si-1L)*dt
    runtime<-list(nodeK=nodeK,node.seedbankK=node.seedbankK,weights=weights,nodetransition=nodetransition,managing=managing,timestep=si,Ntimesteps=nts)
    mix<-if(is.null(StageMixing))sm else StageMixing
    for(ss in seq_len(nsub)){
      ahu<-matrix(0,nu,length(agents),dimnames=list(NULL,names(agents)));nextA<-Astate
      for(nm in names(agents)){a<-agents[[nm]];rfA<-.inapest_tm_cbr_agent_rate_function(br[[nm]],a,si,biocontrol_context);expo<-.inapest_tm_cbr_attacker_exposure(Astate[[nm]],tt,h,rfA,a$AttackStage);ar<-.inabc_resolve_node(a$AttackRate,si,biocontrol_context,"AttackRate",a);nodeh<-ar*(expo/h);Hmat<-matrix(0,nn,D);Hmat[,.inapest_tm_target_stages(a,biocontrol_context)]<-nodeh;ahu[,nm]<-.inapest_tm_flat(Hmat);nextA[[nm]]<-INApestStochasticCompartmentStep(Astate[[nm]],tt,h,rfA)$State}
      rfH<-function(t,state,...).inapest_tm_rate_model(t,state,hf,pars,if(cp)pr else NULL,if(cp)Pathogen else NULL,si,nts,nn,D,mix,ahu,runtime)
      hz<-INApestStochasticCompartmentStep(Hstate,tt,h,rfH);Hstate<-hz$State
      if(cp&&"pathogen"%in%colnames(hz$Exits))deaths<-deaths+.inapest_tm_unflat(hz$Exits[,"pathogen"],nn,D)
      for(nm in names(agents)){cause<-paste0("bio:",nm);killed<-if(cause%in%colnames(hz$Exits))as.integer(hz$Exits[,cause])else integer(nu);km<-.inapest_tm_unflat(killed,nn,D);attacks[[nm]]<-attacks[[nm]]+km;recnode<-rowSums(km)*as.integer(agents[[nm]]$OffspringPerAttack);nextA[[nm]][,agents[[nm]]$RecruitStage]<-nextA[[nm]][,agents[[nm]]$RecruitStage]+recnode}
      Astate<-nextA;tt<-tt+h
    }
    N1<-.inapest_tm_unflat(rowSums(Hstate),nn,D);.inapest_tm_capacity_check(N1,nodeK,node.seedbankK,weights,tol,"Coupled Vertebrate RK state")
    if(cp){st1<-.inapest_tm_pathogen_array(Hstate,nn,D);P0<-.inapest_tm_transport_pathogen(Pathogen);tr<-pdisc(nodetransition=nodetransition,weights=weights,sddprob=sddprob,nodeenvestabprob=nodeenvestabprob,n0=N1,lddprob=lddprob,lddrate=lddrate,nodeK=nodeK,node.seedbankK=node.seedbankK,nodepropaguleestablishment=nodepropaguleestablishment,nodespreadreduction=nodespreadreduction,nodefecundityreduction=nodefecundityreduction,nodecontrolfecundityreduction=nodecontrolfecundityreduction,nodebirthmean=nodebirthmean,nodebirthmothers=nodebirthmothers,managing=managing,MaxInteger=MaxInteger,transition_sddprob=transition_sddprob,transition_lddprob=transition_lddprob,transition_lddrate=transition_lddrate,BlockedTransitionMortality=BlockedTransitionMortality,DispersalDensityFactor=DispersalDensityFactor,pathogen_state=st1,Pathogen=P0,timestep=si,Ntimesteps=nts,StageMixing=mix);Nout<-tr$N;Pout<-tr$PathogenState}else{Nout<-disc(nodetransition=nodetransition,weights=weights,sddprob=sddprob,nodeenvestabprob=nodeenvestabprob,n0=N1,lddprob=lddprob,lddrate=lddrate,nodeK=nodeK,node.seedbankK=node.seedbankK,nodepropaguleestablishment=nodepropaguleestablishment,nodespreadreduction=nodespreadreduction,nodefecundityreduction=nodefecundityreduction,nodecontrolfecundityreduction=nodecontrolfecundityreduction,nodebirthmean=nodebirthmean,nodebirthmothers=nodebirthmothers,managing=managing,MaxInteger=MaxInteger,transition_sddprob=transition_sddprob,transition_lddprob=transition_lddprob,transition_lddrate=transition_lddrate,BlockedTransitionMortality=BlockedTransitionMortality,DispersalDensityFactor=DispersalDensityFactor);Pout<-NULL}
    # Agent spatial movement is intentionally deferred to the parent Vertebrate Node boundary after Interaction.
    impact_att<-lapply(names(agents),function(nm){z<-attacks[[nm]];dimnames(z)<-list(NULL,as.character(seq_len(D)));z});names(impact_att)<-names(agents);recnode<-lapply(names(agents),function(nm)as.integer(rowSums(attacks[[nm]])*agents[[nm]]$OffspringPerAttack));names(recnode)<-names(agents);impact<-list(AttacksByAgent=impact_att,RecruitsByAgent=vapply(recnode,sum,integer(1)),RecruitsByAgentNode=recnode)
    out<-list(N=matrix(as.integer(Nout),nn,D),BiocontrolState=Astate,BiocontrolImpact=impact,PathogenDeaths=matrix(as.integer(deaths),nn,D),NewInfections=matrix(NA_integer_,nn,D),CoupledRK=list(PreTransitionHost=N1,Attacks=attacks,NSubsteps=nsub,InternalStep=h,NewInfectionsDiagnostic="not event-counted in continuous bridge",AgentMovement="deferred to post-Interaction vertebrate boundary"));if(cp)out$PathogenState<-Pout;out
  }
  attr(f,"INApestVNRK4CoupledBiologyLocalDynamics")<-list(Version="0.8",StateMode="integer-coupled",CouplesPathogen=cp,Boundary="continuous local biology then vertebrate stage transport; agent movement deferred until after Interaction")
  attr(f,"INApestCouplesBiocontrol")<-TRUE;attr(f,"INApestCouplesPathogen")<-cp;attr(f,"INApestRunWhenEmpty")<-TRUE;class(f)<-c("INApestVNRK4CoupledBiologyLocalDynamics","function");f
}
